### ISSUE TITLE
Code Indentation

### ISSUE THREAD

**Issue by zchauvin** [aidaylanan/SAfeR#3]
The link below shows a segment of code that isn't properly indented - make sure that you use standard indenting to make your code more legible. Check out this [style guide](http://adv-r.had.co.nz/Style.html) by Hadley Wickham himself for details on indentation. 

https://github.com/aidaylanan/SAfeR/blob/585150fc80ad2d046bfbecd2523579108e5fa174/R/trend_line.R#L13-L20

**Comment by jasonchongg** [comment]
Fixed
